stages:
  - deploy

variables:
  STACK_NAME: "ec2-stack"
  AWS_DEFAULT_REGION: "us-east-1"

set_identity:
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  stage: deploy
  id_tokens:
    AWS_ID_TOKEN:
      aud: https://gitlab.com
  before_script:
    - >
      STS=($(aws sts assume-role-with-web-identity
      --role-arn $AWS_ROLE_ARN
      --region $AWS_DEFAULT_REGION
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $AWS_ID_TOKEN
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - export AWS_ACCESS_KEY_ID="${STS[0]}"
    - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
    - export AWS_SESSION_TOKEN="${STS[2]}"
  script:
    - aws sts get-caller-identity
    - |
      if aws cloudformation describe-stacks --stack-name ${STACK_NAME} >/dev/null 2>&1; then
        aws cloudformation delete-stack --stack-name ${STACK_NAME}
        aws cloudformation wait stack-delete-complete --stack-name ${STACK_NAME}
      else
        echo "Stack ${STACK_NAME} does not exist."
      fi
    - |
      aws cloudformation --region ${AWS_DEFAULT_REGION} create-stack \
      --stack-name $STACK_NAME --template-body file://ec2-setup.yml \
      --parameters \
      ParameterKey=SSHKeyNameParameter,ParameterValue="${SSH_KEY_NAME_PARAMETER}" \
      ParameterKey=SSHPublicKeyValueParameter,ParameterValue="$(echo "${SSH_PUBLIC_KEY_VALUE_PARAMETER}" | base64 -d)"
