AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  GitLabProjectName:
    Type: String
    Description: "The full name of board/name + / + repo name"

  # GitLabWebSite:
  #   Type: String
  #   Description: "Your corporate gitlab website without https:// or leave it empty"
  #   Default: "gitlab.com"

Resources:
  GitLabCIProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Sub https://devops-gitlab.inno.ws
      ClientIdList:
        - !Sub https://devops-gitlab.inno.ws

  GitlabCIRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/devops-gitlab.inno.ws
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                devops-gitlab.inno.ws:sub: !Sub project_path:${GitLabProjectName}:ref_type:branch:ref:master
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
